### ISSUE TITLE
Error message: S3ResponseError

### ISSUE THREAD

**Issue by skovhus** [hatch-sh/hatch#41]
We need a better error message:

```
Traceback (most recent call last):
  File "/usr/local/bin/hatch", line 11, in <module>
    load_entry_point('hatch-cli==0.0.1b3', 'console_scripts', 'hatch')()
  File "/usr/local/lib/python2.7/dist-packages/hatch/cli.py", line 112, in run
    website_command(arguments)
  File "/usr/local/lib/python2.7/dist-packages/hatch/cli.py", line 71, in website_command
    website.deploy()
  File "/usr/local/lib/python2.7/dist-packages/hatch/services/website.py", line 71, in deploy
    bucket = boto.connect_s3().get_bucket(self.name)
  File "/usr/local/lib/python2.7/dist-packages/boto/s3/connection.py", line 506, in get_bucket
    return self.head_bucket(bucket_name, headers=headers)
  File "/usr/local/lib/python2.7/dist-packages/boto/s3/connection.py", line 553, in head_bucket
    response.status, response.reason, body)
boto.exception.S3ResponseError: S3ResponseError: 400 Bad Request
```

https://travis-ci.org/hatch-sh/hatch.sh/builds/248682907#L516

Bug is probably related to:
https://github.com/hatch-sh/hatch.sh/commit/7d1f6ae1fa30ff89a7d4df7ca91964369382ed33

**Comment by mads-hartmann** [comment]
@skovhus This only occurred in v0.0.1b3 right?

**Comment by skovhus** [comment]
Master didn't work either.

**Comment by skovhus** [comment]
Sorry. Wrong ticket. : ) Yes master works
